---
title: "Lecture8"
author: "Natalie Benoit"
date: "3/9/2021"
output: html_document
---

```{r}
library(dplyr)
library(tidyverse)
```

Conditons and iterations
Operators:
==, !=
<, >
<=, >=
%in%


## Exercice 1
```{r}
w <- 10.2
x <- 1.3
y <- 2.8
z <- 17.5
colors <- c("red", "blue", "green")
masses <- c(45.2, 36.1, 27.8, 81.6, 42.4)
dna1 <- "attattaggaccaca"
dna2 <- "attattaggaacaca"

#w is greater than 10
w > 10
color = "green"
x > y
masses > 40
```



If statements 
Conditional statements generate logical values to filter inputs.
if statements use conditional statements to control flow of the program.
```{r}
x <- 6
if (x > 5){
  x <- x^2
}
x


x = 4
if (x > 5){
  x <- x^2
}
x

veg_type <- "tree"
volume <- 16.08
if (veg_type == "tree") {
  mass <- 2.65 * volume^0.9
  }
mass

```


#Exercise 2
```{r}
age_class = "sapling"
if (age_class == "sapling"){
  y <- 10
}
y
```



Alternative conditioning 
Often want to chose one of several options
Can add more conditions and associated actions with else if
```{r}
veg_type <- "grass"
volume <- 16.08
if (veg_type == "tree") {
  mass <- 2.65 * volume^0.9
} else if (veg_type == "grass") {
  mass <- 0.65 * volume^1.2
}
mass
```


## Excercise 3
```{r}
age_class <- "seedling"
if(age_class == "seedling"){
  y <- 5
}
y


age_class = "sapling"
if (age_class == "sapling"){
  y <- 10
}
y

age_class = "other"
if (age_class == "other"){
  y <- 0
}
y
```


