---
title: "Lecture_4"
author: "Natalie Benoit"
date: "2/23/2021"
output: html_document
---

```{r}
library(dplyr)
library(tidyverse)
```

# download data
```{r cars}
surveys <- read_csv("data/surveys.csv")
```

# subsetting data, filtering, and mutating
```{r}
select(surveys, year, month, day)
filter(surveys, species_id == "DS")
mutate(surveys, hindfoot_length_cm = hindfoot_length / 10)

# manupulations stored in a new variable 
surveys_plus <- mutate(surveys,
                       hindfoot_length_cm = hindfoot_length / 10)
```

#exercise 1
#names & structure (1-2)
```{r}
names(shrub_volume_data)
str(shrub_volume_data)
```

#selecting data, filtering, and creating a new tibble ()
```{r}
select(shrub_volume_data, length)
select(shrub_volume_data, site, experiment)
filter(shrub_volume_data, height > 5)

shrub_data_w_vols <- mutate(shrub_volume_data,
                       volume = length * width * height)
```


#basic aggregation 
```{r}
group_by(surveys, species_id)
surveys_by_species <- group_by(surveys, species_id)
summarize(surveys_by_species, abundance = n())
```

#grouping multiple columns
```{r}
surveys_by_species_plot <- group_by(surveys, species_id, plot_id)
summarize(surveys_by_species, abundance = n())
species_weight <- summarize(surveys_by_species, avg_weight = mean(weight))
species_weight <- summarize(surveys_by_species,
                            avg_weight = mean(weight, na.rm = TRUE))
na.omit(species_weight)
ds_data <- filter(surveys, species_id == "DS")
ds_data_by_year <- group_by(ds_data, year)
ds_weight_by_year <- summarize(ds_data_by_year,
                               avg_weight = mean(weight, na.rm = TRUE))

```


# Exercise 2 (1-3)
```{r}
select(surveys, year, month, day, species_id)
na.omit(surveys, weight)
weight_kg <- select(surveys, species_id, year) 

weight_kg_mu <- mutate(surveys, weight = weight / 1000)

surveys_SH <- filter(surveys, species_id == 'SH')
```


# 4-6
```{r}
surveys_sp_id <- group_by(surveys, year)
summarize(surveys_sp_id, species_id)
surveys_mean_mass <- filter(surveys, species_id =="D0") %>%
  group_by(year) %>%
  summarise(mean_weight = mean(weight))
```


# pipes
```{r}
surveys %>%
  filter(species_id == "DS", !is.na(weight))

ds_weight_by_year <- surveys %>%
  filter(species_id == "DS") %>%
  group_by(year) %>%
  summarize(avg_weight = mean(weight, na.rm = TRUE))
```


#exercise 3
```{r}
no_null_weights <- surveys %>%
  select(year, species_id, weight)%>%
  mutate(weight.kg = weight / 1000)%>%
  select(-weight) 
  weight_kg<-na.omit(no_null_weights)

species_SH <- surveys %>%
  select(year, month, day, species_id) %>%
  filter(species_id == "SH")

species_byID <- surveys %>% 
  group_by(species_id) %>%
  summarize(speceies_id = n())

species_byID_year <- surveys %>%
  group_by(species_id, year) %>%
  summarize(speceies_id = n())

dO_weight_year <- surveys %>%
  filter(species_id == "DO") %>%
  group_by(year) %>%
  summarize(avg_weight = mean(weight, na.rm = TRUE))
```





